import type { Metadata } from 'next';
import { Noto_Sans_TC } from 'next/font/google';
import './globals.css';
import { Navigation } from '../components/Navigation';

const noto_sans_tc = Noto_Sans_TC({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={noto_sans_tc.className}>
        <Navigation />
        <div className='container'>{children}</div>
      </body>
    </html>
  );
}
